on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: CI

env:
  MY_LOG_LEVEL: warn
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: cargo fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clippy
        run: cargo clippy --tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose